title: Anarhynchus
name_he: Anarhynchus
name_la: Anarhynchus
name_hu: 'Ferdecsőrű lile'
category: bird
hero_image: birds/img_7710-copy.jpg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1729756709
blueprint: genus
