title: 'אנפה ירוקה'
name_he: 'אנפה ירוקה'
name_la: Butorides
name_hu: Butorides
category: bird
hero_image: birds/butorides-striata.jpg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1731865429
blueprint: genus
