title: Lullula
name_he: Lullula
name_la: Lullula
name_hu: Lullula
category: bird
hero_image: birds/lullula-arborea.jpg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1731587523
blueprint: genus
