title: צוקית
name_he: צוקית
name_la: Monticola
name_hu: Monticola
category: bird
hero_image: birds/monticola-solitarius.jpg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1742644873
blueprint: genus
