title: כפן
name_he: כפן
name_la: Platalea
name_hu: Kanalasgémformák
category: bird
hero_image: birds/platalea-leucorodia.jpeg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1742646129
blueprint: genus
