title: כוכית
name_he: כוכית
name_la: Riparia
name_hu: Riparia
category: bird
hero_image: birds/riparia-riparia.png
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1753282421
blueprint: genus
