title: סולנום
name_he: סולנום
name_la: 'Solanum L.'
name_hu: Csucsor
category: flower
hero_image: flowers/solanum-elaeagnifolium-cav.jpeg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1725376471
blueprint: genus
