title: מרית
name_he: מרית
name_la: Spatula
name_hu: Spatula
category: bird
hero_image: birds/spatula-querquedula.jpg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1744569798
blueprint: genus
