title: סטרנולה
name_he: סטרנולה
name_la: Sternula
name_hu: Sternula
category: bird
hero_image: birds/sternula-albifrons.jpg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1744568831
blueprint: genus
