title: טדורנה
name_he: Tadorna
name_la: Tadorna
name_hu: Ásólúd
category: bird
hero_image: birds/tadorna-ferruginea.png
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1735304419
blueprint: genus
