title: ברווזיים
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1715145166
blueprint: family
name_he: ברווזיים
name_la: Anatidae
name_hu: Récefélék
category: bird
hero_image: birds/anas-clypeata.jpeg
