title: פלמינגואיים
name_he: פלמינגואיים
name_la: Phoenicopteridae
name_hu: Flamingófélék
category: bird
hero_image: birds/phoenicopterus-roseus.jpg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1730825004
blueprint: family
