title: רמיזיים
name_he: רמיזיים
name_la: Remizidae
name_hu: Függőcinege-félék
category: bird
hero_image: birds/remiz-pendulinus.jpg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1731864954
blueprint: family
