title: סולניים
name_he: סולניים
name_la: Solanaceae
name_hu: Burgonyafélék
category: flower
hero_image: flowers/solanum-elaeagnifolium-cav.jpeg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1725376338
blueprint: family
