title: פלמינגואים
name_he: פלמינגואים
name_la: Phoenicopteriformes
name_hu: Flamingóalakúak
category: bird
hero_image: birds/phoenicopterus-roseus.jpg
updated_by: 9e099556-0278-43e4-b8a2-64728f12886d
updated_at: 1730824940
blueprint: order
